# Generated by Django 3.0.8 on 2020-08-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200727_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=100), unique=True),
        ),
    ]
