# Generated by Django 3.0.8 on 2020-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_topicmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
