# Generated by Django 3.0.8 on 2020-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_topicmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=100), unique=True),
        ),
    ]
