# Generated by Django 3.0.8 on 2020-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200808_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
