# Generated by Django 3.0.8 on 2020-08-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200808_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicmodel',
            unique_together={('title', 'url')},
        ),
    ]
