# Generated by Django 3.0.8 on 2020-08-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200808_1150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='url',
        ),
    ]
