# Generated by Django 3.0.8 on 2020-08-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200808_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='content',
        ),
    ]
